//
// Created by kier on 2018/11/3.
//

#ifndef TENSORSTACK_RUNTIME_INSTRUCTION_INSTRUCTION_FACTORY_H
#define TENSORSTACK_RUNTIME_INSTRUCTION_INSTRUCTION_FACTORY_H


namespace ts {

}


#endif //TENSORSTACK_RUNTIME_INSTRUCTION_INSTRUCTION_FACTORY_H
