set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR aarch64)

set(ARM_VER aarch64)
set(ARM_ABI gnu)

#set(CMAKE_SYSROOT /usr/${ARM_VER}-linux-${ARM_ABI})
set(CMAKE_FIND_ROOT_PATH /usr/${ARM_VER}-linux-${ARM_ABI})
#set(CMAKE_STAGING_PREFIX /usr/${ARM_VER}-linux-${ARM_ABI})

set(CMAKE_C_COMPILER ${ARM_VER}-linux-${ARM_ABI}-gcc)
set(CMAKE_CXX_COMPILER ${ARM_VER}-linux-${ARM_ABI}-g++)

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)

